### PR TITLE
Add 3 new additonal features! ~:D

### PR DESCRIPTION
**Pull request by JamesEU**
~ Just 3 nice features I've used previously good to have for some servers.

### CODE REVIEW

**Comment by JaredScar** [comment]
Is this tested?

**Comment by JamesEU** [comment]
> Is this tested?

Yeah has been tested was in an old anti-cheat of mine. :D

**Comment by JamesEU** [comment]
Works brilliantly.

**Comment by JaredScar** [comment]
Accepted, thanks!

**Pull request merged**
