### PR TITLE
Added Anti resource start and stop.

### PR DESCRIPTION
**Pull request by KillaNAdev**
Added anti resource start and stop to the ac (The snippet I added was from my anticheat ) 😄

### CODE REVIEW

**Comment by JaredScar** [comment]
I don't think this code will work. Has this been tested standalone?

**Comment by KillaNAdev** [comment]
Yes I have tested it and it worked for me.

**Comment by KillaNAdev** [comment]
I just realized I would need to edit the ban messages because they say my ac but yea

**Comment by JaredScar** [comment]
> I just realized I would need to edit the ban messages because they say my ac but yea

This is exactly why I asked. I saw events triggered that would do nothing lol....

**Comment by JaredScar** [comment]
This still won't work though. You trigger events that aren't even defined anywhere (`"VAC:resourcestopandstart"`). The code is a bit sloppy too. Can you try again with a cleaner code approach? Thanks.

**Pull request closed without merging**
